language: php
sudo: false
dist: trusty
php:
  - 7.4
  - nightly
  
node_js:
  - 12

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - node_modules
    - vendor

before_install:
  - composer self-update
  - npm i

install:
  - node -v
  - composer install -o --prefer-dist --no-interaction

script:
  - npm run dev
  - npm run rmdist
  - npm run prod
  - composer test
